stages:
    - deploy

variables:
    TAG: $CI_BUILD_REF_SLUG

pages:
  tags:
    - docker
  image: python:3
  stage: deploy
  before_script:
    - apt update && apt install graphviz
    - pip install -r docs/requirements.txt
    - cd docs
  script:
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
