version: "3.5"

services:
  postfix:
    image: dev.cryptec.at:5000/infrastructure/mailstack/postfix
    build: ./postfix
    env_file:
      - ./postfix.env
    ports:
      - "25:25"
      - "587:587"
    networks:
      - internal
      - auth.mailstack.postfix
    volumes:
      - type: volume
        source: certificates
        target: /etc/certificates
        read_only: yes

  dovecot:
    image: dev.cryptec.at:5000/infrastructure/mailstack/dovecot
    build: ./dovecot
    env_file:
      - ./dovecot.env
    ports:
      - "143:143"
      - "993:993"
    volumes:
      - type: volume
        source: mailboxes
        target: /var/vmail
      - type: volume
        source: certificates
        target: /etc/certificates
        read_only: yes
    networks:
      - internal
      - auth.mailstack.dovecot

  sogo:
    image: dev.cryptec.at:5000/infrastructure/mailstack/sogo
    build: ./sogo
    user: sogo
    env_file:
      - ./sogo.env
      - ./database.env
    networks:
      - internal
      - database
      - sogo.cache
      - sogo.proxy
      - auth.mailstack.sogo
    volumes:
      - type: volume
        source: sogo-web
        target: /usr/lib/GNUstep/SOGo/WebServerResources

  memcached:
    image: memcached:alpine
    networks:
      - sogo.cache

  postgres:
    image: postgres
    restart: always
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/pgdata
    env_file:
      - ./database.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - database

  caddy:
    image: dev.cryptec.at:5000/infrastructure/mailstack/caddy
    build: ./caddy
    networks:
      - sogo.proxy
      - expose.mailstack.caddy
    volumes:
      - type: volume
        source: sogo-web
        target: /etc/sogo/resources

  rspamd:
    image: dev.cryptec.at:5000/infrastructure/mailstack/rspamd
    build: ./rspamd
    networks:
      - internal
      - rspamd.database
      - expose.mailstack.rspamd
    env_file:
      - ./rspamd.env
    volumes:
      - rspamd-data:/var/lib/rspamd

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - rspamd.database
    volumes:
      - redis-data:/data

volumes:
  mailboxes:
  postgres-data:
  sogo-web:
  rspamd-data:
  redis-data:
  certificates:
    external:
      name: certificates

networks:
  internal:
  database:
  sogo.proxy:
  sogo.cache:
  rspamd.database:

  auth.mailstack.postfix:
    external:
      name: auth.mailstack.postfix
  auth.mailstack.dovecot:
    external:
      name: auth.mailstack.dovecot
  auth.mailstack.sogo:
    external:
      name: auth.mailstack.sogo

  expose.mailstack.caddy:
    external:
      name: expose.mailstack.caddy
  expose.mailstack.rspamd:
    external:
      name: expose.mailstack.rspamd
