version: "3.5"
services:
  postfix:
    build: ./postfix
    env_file:
      - ./postfix.env
    ports:
      - "25:25"
      - "587:587"
    networks:
      - internal
      - auth.mailstack.postfix
    volumes:
      - type: volume
        source: certificates
        target: /etc/certificates
        read_only: yes

  dovecot:
    build: ./dovecot
    env_file:
      - ./dovecot.env
    ports:
      - "143:143"
      - "993:993"
    volumes:
      - type: volume
        source: mailboxes
        target: /var/vmail
      - type: volume
        source: certificates
        target: /etc/certificates
        read_only: yes
    networks:
      - internal
      - auth.mailstack.dovecot

  sogo:
    build: ./sogo
    user: sogo
    env_file:
      - ./sogo.env
      - ./database.env
    networks:
      - internal
      - database
      - cache
      - proxy
      - auth.mailstack.sogo
    volumes:
      - type: volume
        source: sogo-web
        target: /usr/lib/GNUstep/SOGo/WebServerResources

  memcached:
    image: memcached:alpine
    networks:
      - cache

  postgres:
    image: postgres
    restart: always
    volumes:
      - type: volume
        source: sogo-data
        target: /var/lib/postgresql/data/pgdata
    env_file:
      - ./database.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - database

  caddy:
    build: ./caddy
    networks:
      - proxy
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - type: volume
        source: sogo-web
        target: /etc/sogo/resources

  rspamd:
    build: ./rspamd
    networks:
      - internal
    ports:
      - "0.0.0.0:11334:11334"

volumes:
  mailboxes:
  sogo-data:
  sogo-web:
  certificates:
    external:
      name: certificates

networks:
  internal:
  database:
  proxy:
  cache:

  auth.mailstack.postfix:
    external:
      name: auth.mailstack.postfix
  auth.mailstack.dovecot:
    external:
      name: auth.mailstack.dovecot
  auth.mailstack.sogo:
    external:
      name: auth.mailstack.sogo
