version: "3.5"
services:
  postfix:
    build: ./postfix
    env_file:
      - ./postfix.env
    ports:
      - "25:25"
      - "587:587"
    networks:
      - internal
      - auth
    volumes:
      - type: volume
        source: certificates
        target: /etc/certificates
        read_only: yes

  dovecot:
    build: ./dovecot
    env_file:
      - ./dovecot.env
    ports:
      - "143:143"
      - "993:993"
    volumes:
      - type: volume
        source: mailboxes
        target: /var/vmail
      - type: volume
        source: certificates
        target: /etc/certificates
        read_only: yes
    networks:
      - internal
      - auth

  sogo:
    build: ./sogo
    user: sogo
    env_file:
      - ./sogo.env
    ports:
      - "80:80"
    networks:
      - internal
      - auth

volumes:
  mailboxes:
  certificates:
    external:
      name: certificates

networks:
  internal:
  auth:
    external:
      name: auth
