vars:
  image_tag:
    default: master
    comment: Docker image tag

  domain:
    default: example.com
    comment: Default Domain

  additional_domains:
    default: []
    comment: additional domains you want to send to and receive mail from.

  address:
    default: mail.example.com
    comment: Web address

  ldap:
    default:
      included: true
      admin_pw: apfel
      search_base: ou=People,dc=example,dc=com
      server: ldap:389
      tls: false
      username_attribute: uid
      user_objectclass: inetOrgPerson
    comment: "Commonly shared ldap settings, don't set ldap protocol here."

  ssl:
    default:
      certificate: self
      cert_path: /etc/certificates/cert.pem
      key_path: /etc/certificates/key.pem
    comment: "SSL related settings. Options: caddy, self"

  caddy:
    default:
      internal: false
      ip_address: '127.0.0.1'
      email: "admin@example.com"
    comment: Caddy available from outside or not? Set ip_address only if caddy is not internal

  postfix:
    default:
      ldap:
        bind_dn: uid=postfix,ou=Services,dc=example,dc=com
        bind_pw: apfel
      relayhost: ""
<<<<<<< HEAD
      skip_rspamd_milter: false
=======
      enable_implicit_tls: false
>>>>>>> Add option to start SMTP port with implicit TLS
    comment: All Settings regarding postfix.

  dovecot:
    default:
      ldap:
        bind_dn: uid=dovecot,ou=Services,dc=example,dc=com
        bind_pw: apfel
      imap_login_performance_mode: "NO"
      publish_sieve_port: "NO"
      mail_max_userip_connections: "10"
    comment: Dovecot settings

  rspamd:
    default:
      controller:
        password: none
        enable_password: none
      webinterface:
        enable: true
        internal: false
        domain: rspamd.example.com
    comment: Rspamd settings

  sogo:
    default:
      ldap:
        bind_dn: uid=sogo,ou=Services,dc=example,dc=com
        bind_pw: apfel
      debug: 'NO'
      worker_count: 3
      appointment_send_email_notifications: 'NO'
      acls_send_email_notifications: 'NO'
      folders_send_email_notifications: 'NO'
      sx_vmem_limit: '384'
      maximum_sync_window_size: '99'
      maximum_sync_response_size: '512'
    comment: SOGo settings

  postgres:
    default:
      user: sogo
      password: apfel
      db: sogo
      max_connections: 50
    comment: Database for sogo. All user data such as calendars/addressbooks are stored here.

  compose:
    default:
      include_build_settings: false
    comment: Settings regarding compose file settings

files:
  docker-compose.template.yml: docker-compose.yml
  ldap.template.env: ldap.env
