vars:
  domain:
    default: example.com
    comment: Default domain.

  address:
    default: mail.example.com
    comment: Web address

  ldap:
    default:
      search_base: ou=People,dc=example,dc=com
      server: ldap:389
      tls: false
    comment: Commonly shared ldap settings, don't set ldap protocol here.

  ssl:
    default:
      certificate: caddy
      cert_path: /etc/certificates/fullchain.pem
      key_path: /etc/certificates/privkey.pem
    comment: "SSL related settings. Options: caddy, self, off"

  caddy:
    default:
      exposed: true
      ip_address: '127.0.0.1'
      email: "admin@example.com"
    comment: Caddy available from outside or not? Set ip_address only if caddy is exposed

  postfix:
    default:
      ldap:
        bind_dn: uid=postfix,ou=Services,dc=example,dc=com
        bind_pw: apfel
    comment: All Settings regarding postfix.

  dovecot:
    default:
      ldap:
        bind_dn: uid=dovecot,ou=Services,dc=example,dc=com
        bind_pw: apfel
    comment: Dovecot settings

  rspamd:
    default:
      controller:
        password: none
        enable_password: none
      webinterface:
        enable: true
        publish: false
        domain: rspamd.example.com
    comment: Rspamd settings

  sogo:
    default:
      ldap:
        bind_dn: uid=sogo,ou=Services,dc=example,dc=com
        bind_pw: apfel
      debug: 'NO'
    comment: SOGo settings

  postgres:
    default:
      user: sogo
      password: apfel
      db: sogo
    comment: Database for sogo. All user data such as calendars/addressbooks are stored here.

files:
  docker-compose.template.yml: docker-compose.yml
